# Generated by Django 5.2.8 on 2026-03-24 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_app.category'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
